export type Platform = 'cross' | 'web' | 'mobile' | 'desktop';
export type Difficulty = 'easy' | 'medium' | 'hard';
export type TaxonomyCategory =
  | 'action_affordance'
  | 'visibility'
  | 'accessibility'
  | 'timing'
  | 'navigation'
  | 'feedback'
  | 'gesture'
  | 'forms'
  | 'grounding';

export interface FailureMeta {
  defectCode: string;
  title: string;
  platform: Platform;
  taxonomyCategory: TaxonomyCategory;
  difficulty: Difficulty;
  implemented: boolean;
  // Traces this entry back to the shared F-code taxonomy (docs/failure-implementation-plan.md).
  // Absent for entries that predate that taxonomy and have no corresponding F-code.
  assessmentRef?: string;
}

// Web app includes cross-platform and web-specific failures only.
export const failures: Record<string, FailureMeta> = {
  'non-clickable-normal-cta': {
    defectCode: 'B_NON_CLICKABLE_NORMAL_CTA',
    title: 'Non-clickable but visually normal CTA',
    platform: 'cross',
    taxonomyCategory: 'action_affordance',
    difficulty: 'easy',
    implemented: true,
  },
  'click-no-visible-effect': {
    defectCode: 'B_CLICK_NO_VISIBLE_EFFECT',
    title: 'No visible feedback on action trigger',
    platform: 'cross',
    taxonomyCategory: 'feedback',
    difficulty: 'easy',
    implemented: true,
    assessmentRef: 'F7.4',
  },
  'action-not-exposed-in-tree': {
    defectCode: 'M_ACTION_NOT_EXPOSED_IN_TREE',
    title: 'Inaccessible element from DOM/a11y tree',
    platform: 'cross',
    taxonomyCategory: 'accessibility',
    difficulty: 'easy',
    implemented: true,
    assessmentRef: 'F1.5',
  },
  'aria-hidden-swallows-control': {
    defectCode: 'M_ARIA_HIDDEN_SWALLOWS_CONTROL',
    title: 'Interactive node hidden by aria-hidden misuse',
    platform: 'web',
    taxonomyCategory: 'accessibility',
    difficulty: 'easy',
    implemented: true,
    assessmentRef: 'F1.3',
  },
  'native-dialog-outside-dom': {
    defectCode: 'B_NATIVE_DIALOG_OUTSIDE_DOM',
    title: 'Native browser dialog outside page DOM',
    platform: 'web',
    taxonomyCategory: 'accessibility',
    difficulty: 'easy',
    implemented: true,
    assessmentRef: 'F1.4',
  },
  'low-contrast-boundary': {
    defectCode: 'V_LOW_CONTRAST_BOUNDARY',
    title: 'Low color contrast',
    platform: 'cross',
    taxonomyCategory: 'visibility',
    difficulty: 'easy',
    implemented: true,
    assessmentRef: 'F1.6',
  },
  'missing-accessible-name': {
    defectCode: 'M_MISSING_ACCESSIBLE_NAME',
    title: 'Key element missing accessible name',
    platform: 'cross',
    taxonomyCategory: 'accessibility',
    difficulty: 'easy',
    implemented: false,
  },
  'blocking-modal-no-close': {
    defectCode: 'B_BLOCKING_MODAL_NO_CLOSE',
    title: 'Blocking modal, tiny or no close affordance',
    platform: 'cross',
    taxonomyCategory: 'visibility',
    difficulty: 'easy',
    implemented: true,
    assessmentRef: 'F9.1',
  },
  'async-content-late-render': {
    defectCode: 'B_ASYNC_CONTENT_LATE_RENDER',
    title: 'Async content renders after agent snapshots DOM',
    platform: 'cross',
    taxonomyCategory: 'timing',
    difficulty: 'medium',
    implemented: false,
  },
  'visual-occlusion-non-blocking-overlay': {
    defectCode: 'V_VISUAL_OCCLUSION_NON_BLOCKING_OVERLAY',
    title: 'Visual occlusion by non-blocking overlay',
    platform: 'web',
    taxonomyCategory: 'visibility',
    difficulty: 'easy',
    implemented: true,
    assessmentRef: 'F9.3',
  },
  'misleading-label-text': {
    defectCode: 'M_MISLEADING_LABEL_TEXT',
    title: 'Misleading visuals or iconography',
    platform: 'web',
    taxonomyCategory: 'accessibility',
    difficulty: 'easy',
    implemented: false,
  },
  'hidden-behind-menu-only-path': {
    defectCode: 'B_HIDDEN_BEHIND_MENU_ONLY_PATH',
    title: 'Important links hidden in subtle menu',
    platform: 'web',
    taxonomyCategory: 'navigation',
    difficulty: 'medium',
    implemented: true,
    assessmentRef: 'F5.1',
  },
  'duplicate-labels-different-actions': {
    defectCode: 'M_DUPLICATE_LABELS_DIFFERENT_ACTIONS',
    title: 'Unclear icon-only critical CTA',
    platform: 'web',
    taxonomyCategory: 'accessibility',
    difficulty: 'medium',
    implemented: false,
  },
  'static-element-styled-actionable': {
    defectCode: 'V_STATIC_ELEMENT_STYLED_ACTIONABLE',
    title: 'Static element styled as actionable',
    platform: 'web',
    taxonomyCategory: 'action_affordance',
    difficulty: 'easy',
    implemented: true,
    assessmentRef: 'F2.1',
  },
  'actionable-element-styled-static': {
    defectCode: 'V_ACTIONABLE_ELEMENT_STYLED_STATIC',
    title: 'Actionable element styled as static',
    platform: 'web',
    taxonomyCategory: 'action_affordance',
    difficulty: 'easy',
    implemented: true,
    assessmentRef: 'F2.2',
  },
  'overloaded-icon-multi-purpose': {
    defectCode: 'M_OVERLOADED_ICON_MULTI_PURPOSE',
    title: 'Overloaded icon (multiple purposes)',
    platform: 'web',
    taxonomyCategory: 'accessibility',
    difficulty: 'medium',
    implemented: true,
    assessmentRef: 'F2.3',
  },
  'rebrand-breaks-grounding': {
    defectCode: 'M_REBRAND_BREAKS_GROUNDING',
    title: 'Rebrand breaks entity grounding',
    platform: 'cross',
    taxonomyCategory: 'accessibility',
    difficulty: 'medium',
    implemented: true,
    assessmentRef: 'F2.4',
  },
  'dom-order-visual-mismatch': {
    defectCode: 'V_DOM_ORDER_VISUAL_MISMATCH',
    title: 'Visual layout overlaps DOM order',
    platform: 'web',
    taxonomyCategory: 'visibility',
    difficulty: 'medium',
    implemented: true,
    assessmentRef: 'F3.2',
  },
  'popup-outside-dom-hierarchy': {
    defectCode: 'M_POPUP_OUTSIDE_DOM_HIERARCHY',
    title: 'Popup not represented in DOM hierarchy',
    platform: 'web',
    taxonomyCategory: 'accessibility',
    difficulty: 'medium',
    implemented: true,
    assessmentRef: 'F3.3',
  },
  'dom-present-visually-hidden': {
    defectCode: 'V_DOM_PRESENT_VISUALLY_HIDDEN',
    title: 'DOM-visible but visually hidden element',
    platform: 'web',
    taxonomyCategory: 'visibility',
    difficulty: 'easy',
    implemented: true,
    assessmentRef: 'F3.4',
  },
  'gesture-only-no-visible-cue': {
    defectCode: 'B_GESTURE_ONLY_NO_VISIBLE_CUE',
    title: 'Non-standard activation gesture, no visible cue',
    platform: 'web',
    taxonomyCategory: 'gesture',
    difficulty: 'medium',
    implemented: true,
    assessmentRef: 'F4.1',
  },
  'combobox-uncommitted-value': {
    defectCode: 'B_COMBOBOX_UNCOMMITTED_VALUE',
    title: 'Combobox value uncommitted without explicit selection',
    platform: 'web',
    taxonomyCategory: 'forms',
    difficulty: 'medium',
    implemented: true,
    assessmentRef: 'F4.2',
  },
  'heading-label-mismatch': {
    defectCode: 'M_HEADING_LABEL_MISMATCH',
    title: 'Heading/label mismatch breaks grounding',
    platform: 'web',
    taxonomyCategory: 'grounding',
    difficulty: 'easy',
    implemented: true,
    assessmentRef: 'F6.1',
  },
  'cluttered-list-similar-items': {
    defectCode: 'V_CLUTTERED_LIST_SIMILAR_ITEMS',
    title: 'Cluttered list with similar items',
    platform: 'web',
    taxonomyCategory: 'visibility',
    difficulty: 'medium',
    implemented: true,
    assessmentRef: 'F6.2',
  },
  'missing-filter-sort-controls': {
    defectCode: 'B_MISSING_FILTER_SORT_CONTROLS',
    title: 'Missing filter or sort controls',
    platform: 'web',
    taxonomyCategory: 'navigation',
    difficulty: 'medium',
    implemented: true,
    assessmentRef: 'F6.3',
  },
  'unsupported-language-content': {
    defectCode: 'M_UNSUPPORTED_LANGUAGE_CONTENT',
    title: 'Unsupported-language content',
    platform: 'web',
    taxonomyCategory: 'grounding',
    difficulty: 'easy',
    implemented: true,
    assessmentRef: 'F6.4',
  },
  'non-updated-state-after-failed-action': {
    defectCode: 'B_NON_UPDATED_STATE_AFTER_FAILED_ACTION',
    title: 'Non-updated state after failed action',
    platform: 'web',
    taxonomyCategory: 'feedback',
    difficulty: 'medium',
    implemented: true,
    assessmentRef: 'F7.1',
  },
  'vague-validation-error': {
    defectCode: 'M_VAGUE_VALIDATION_ERROR',
    title: 'Vague or non-specific validation error',
    platform: 'web',
    taxonomyCategory: 'forms',
    difficulty: 'easy',
    implemented: true,
    assessmentRef: 'F7.2',
  },
  'required-field-no-indicator': {
    defectCode: 'V_REQUIRED_FIELD_NO_INDICATOR',
    title: 'Required field lacks visible indicator',
    platform: 'web',
    taxonomyCategory: 'forms',
    difficulty: 'easy',
    implemented: true,
    assessmentRef: 'F7.3',
  },
  'unbounded-infinite-scroll': {
    defectCode: 'B_UNBOUNDED_INFINITE_SCROLL',
    title: 'No terminal state / unbounded scroll',
    platform: 'web',
    taxonomyCategory: 'feedback',
    difficulty: 'medium',
    implemented: true,
    assessmentRef: 'F7.5',
  },
  'late-render-outside-viewport': {
    defectCode: 'B_LATE_RENDER_OUTSIDE_VIEWPORT',
    title: 'Dynamically rendered content outside viewport',
    platform: 'web',
    taxonomyCategory: 'timing',
    difficulty: 'medium',
    implemented: true,
    assessmentRef: 'F8.1',
  },
  'slow-load-exceeds-budget': {
    defectCode: 'B_SLOW_LOAD_EXCEEDS_BUDGET',
    title: 'Slow page load exceeds agent timing budget',
    platform: 'web',
    taxonomyCategory: 'timing',
    difficulty: 'medium',
    implemented: true,
    assessmentRef: 'F8.2',
  },
  'popup-after-snapshot': {
    defectCode: 'B_POPUP_AFTER_SNAPSHOT',
    title: 'Popup appears after snapshot',
    platform: 'web',
    taxonomyCategory: 'timing',
    difficulty: 'medium',
    implemented: true,
    assessmentRef: 'F8.3',
  },
  'invisible-overlay-captures-clicks': {
    defectCode: 'V_INVISIBLE_OVERLAY_CAPTURES_CLICKS',
    title: 'Invisible clickable overlay captures input',
    platform: 'web',
    taxonomyCategory: 'visibility',
    difficulty: 'easy',
    implemented: true,
    assessmentRef: 'F9.2',
  },
  'color-transform-defeats-cue': {
    defectCode: 'V_COLOR_TRANSFORM_DEFEATS_CUE',
    title: 'OS-level color transform defeats color grounding',
    platform: 'web',
    taxonomyCategory: 'visibility',
    difficulty: 'medium',
    implemented: true,
    assessmentRef: 'F2.5',
  },
  'ghost-element-stale-list-node': {
    defectCode: 'B_GHOST_ELEMENT_STALE_LIST_NODE',
    title: 'Ghost element in a11y tree',
    platform: 'cross',
    taxonomyCategory: 'accessibility',
    difficulty: 'hard',
    implemented: true,
    assessmentRef: 'F1.1',
  },
  'recycled-row-stale-label': {
    defectCode: 'B_RECYCLED_ROW_STALE_LABEL',
    title: 'Recycled-view stale accessible name',
    platform: 'cross',
    taxonomyCategory: 'accessibility',
    difficulty: 'hard',
    implemented: true,
    assessmentRef: 'F3.1',
  },
  'action-misrouted-across-tabs': {
    defectCode: 'B_ACTION_MISROUTED_ACROSS_TABS',
    title: 'Action misrouted across tabs/windows',
    platform: 'web',
    taxonomyCategory: 'navigation',
    difficulty: 'hard',
    implemented: true,
    assessmentRef: 'F5.2',
  },
  'stale-route-removed-page': {
    defectCode: 'B_STALE_ROUTE_REMOVED_PAGE',
    title: 'Stale route to removed page',
    platform: 'web',
    taxonomyCategory: 'navigation',
    difficulty: 'medium',
    implemented: true,
    assessmentRef: 'F8.4',
  },
};
